In [23]:
pip install plotly

Requirement already satisfied: plotly in c:\users\hp\anaconda3\lib\site-packages (5.2.2)
Requirement already satisfied: six in c:\users\hp\anaconda3\lib\site-packages (from plotly) (1.15.0)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\hp\anaconda3\lib\site-packages (from plotly) (8.0.1)
Note: you may need to restart the kernel to use updated packages.

In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

In [25]:
from plotly.offline import download_plotlyjs, plot, init_notebook_mode, iplot

In [26]:
df = pd.read_csv('Covid_dataset/country_vaccinations.csv')
df

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Albania,ALB,2021-01-10,0.0,0.0,NaN,NaN,NaN,0.00,0.00,NaN,NaN,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/covid19-ministria-e...
1,Albania,ALB,2021-01-11,NaN,NaN,NaN,NaN,64.0,NaN,NaN,NaN,22.0,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/covid19-ministria-e...
2,Albania,ALB,2021-01-12,128.0,128.0,NaN,NaN,64.0,0.00,0.00,NaN,22.0,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/covid19-ministria-e...
3,Albania,ALB,2021-01-13,188.0,188.0,NaN,60.0,63.0,0.01,0.01,NaN,22.0,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/covid19-ministria-e...
4,Albania,ALB,2021-01-14,266.0,266.0,NaN,78.0,66.0,0.01,0.01,NaN,23.0,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/covid19-ministria-e...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6103,Zimbabwe,ZWE,2021-03-08,35518.0,35518.0,NaN,3278.0,2009.0,0.24,0.24,NaN,135.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1370448161...
6104,Zimbabwe,ZWE,2021-03-09,35761.0,35761.0,NaN,243.0,1526.0,0.24,0.24,NaN,103.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1370448161...
6105,Zimbabwe,ZWE,2021-03-10,35901.0,35901.0,NaN,140.0,1133.0,0.24,0.24,NaN,76.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1370448161...
6106,Zimbabwe,ZWE,2021-03-11,36019.0,36019.0,NaN,118.0,766.0,0.24,0.24,NaN,52.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1370448161...
6107,Zimbabwe,ZWE,2021-03-12,36283.0,36283.0,NaN,264.0,708.0,0.24,0.24,NaN,48.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1370448161...

In [27]:
df.describe(include='object')

,country,iso_code,date,vaccines,source_name,source_website
count,6108,5752,6108,6108,6108,6108
unique,133,129,90,25,79,129
top,England,GBR,2021-02-22,"Moderna, Oxford/AstraZeneca, Pfizer/BioNTech",Ministry of Health,https://coronavirus.data.gov.uk/details/health...
freq,89,89,106,1549,1931,445

[Here we obsereved that Moderna, Oxford and pfizer are most used vaccines, now need to check for the null values](http://)

In [28]:
df.isnull().sum()

country                                   0
iso_code                                356
date                                      0
total_vaccinations                     2200
people_vaccinated                      2627
people_fully_vaccinated                3740
daily_vaccinations_raw                 2810
daily_vaccinations                      191
total_vaccinations_per_hundred         2200
people_vaccinated_per_hundred          2627
people_fully_vaccinated_per_hundred    3740
daily_vaccinations_per_million          191
vaccines                                  0
source_name                               0
source_website                            0
dtype: int64

In [29]:
df['total_vaccinations'].dropna(inplace = True)

In [30]:
df['total_vaccinations'].fillna(0,inplace=True)
df

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Albania,ALB,2021-01-10,0.0,0.0,NaN,NaN,NaN,0.00,0.00,NaN,NaN,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/covid19-ministria-e...
1,Albania,ALB,2021-01-11,0.0,NaN,NaN,NaN,64.0,NaN,NaN,NaN,22.0,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/covid19-ministria-e...
2,Albania,ALB,2021-01-12,128.0,128.0,NaN,NaN,64.0,0.00,0.00,NaN,22.0,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/covid19-ministria-e...
3,Albania,ALB,2021-01-13,188.0,188.0,NaN,60.0,63.0,0.01,0.01,NaN,22.0,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/covid19-ministria-e...
4,Albania,ALB,2021-01-14,266.0,266.0,NaN,78.0,66.0,0.01,0.01,NaN,23.0,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/covid19-ministria-e...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6103,Zimbabwe,ZWE,2021-03-08,35518.0,35518.0,NaN,3278.0,2009.0,0.24,0.24,NaN,135.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1370448161...
6104,Zimbabwe,ZWE,2021-03-09,35761.0,35761.0,NaN,243.0,1526.0,0.24,0.24,NaN,103.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1370448161...
6105,Zimbabwe,ZWE,2021-03-10,35901.0,35901.0,NaN,140.0,1133.0,0.24,0.24,NaN,76.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1370448161...
6106,Zimbabwe,ZWE,2021-03-11,36019.0,36019.0,NaN,118.0,766.0,0.24,0.24,NaN,52.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1370448161...
6107,Zimbabwe,ZWE,2021-03-12,36283.0,36283.0,NaN,264.0,708.0,0.24,0.24,NaN,48.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1370448161...

In [31]:
df['total_vaccinations'].sum()

8352979291.0

**Total no. of people vaccinated is 8352979291.0**

In [32]:
df=df[df['country'].apply(lambda x: x not in ['England','Wales','Northern Ireland','Scotland'])]

In [33]:
df['country'].astype('string').value_counts().unique

<bound method Series.unique of United Kingdom    89
Canada            89
Russia            88
Israel            84
United States     83
                  ..
Egypt              7
Mongolia           5
Angola             4
Saint Helena       1
Honduras           1
Name: country, Length: 129, dtype: Int64>

What vaccines are used and in which countries?

In [34]:
df['vaccines'].value_counts()

Moderna, Oxford/AstraZeneca, Pfizer/BioNTech                                          1549
Pfizer/BioNTech                                                                       1149
Oxford/AstraZeneca, Pfizer/BioNTech                                                    515
Oxford/AstraZeneca                                                                     447
Moderna, Pfizer/BioNTech                                                               371
Sputnik V                                                                              203
Sinovac                                                                                197
Pfizer/BioNTech, Sinovac                                                               146
Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/Beijing, Sputnik V                      144
Sinopharm/Beijing                                                                      110
Oxford/AstraZeneca, Sinopharm/Beijing                                                  106
Oxford/AstraZeneca, Sinopharm/Beijing, Sputnik V                                        94
EpiVacCorona, Sputnik V                                                                 88
Johnson&Johnson, Moderna, Pfizer/BioNTech                                               83
Oxford/AstraZeneca, Pfizer/BioNTech, Sputnik V                                          79
Sinopharm/Beijing, Sinopharm/Wuhan, Sinovac                                             76
Moderna, Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/Beijing, Sputnik V              75
Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/Beijing, Sinopharm/Wuhan, Sputnik V      67
Covaxin, Oxford/AstraZeneca                                                             57
Oxford/AstraZeneca, Sinovac                                                             56
Pfizer/BioNTech, Sinopharm/Beijing                                                      45
Pfizer/ BioNTech, Sinopharm/Beijing                                                     33
Johnson&Johnson                                                                         25
Sinopharm/Beijing, Sputnik V                                                            21
Moderna                                                                                 16
Name: vaccines, dtype: int64

In [35]:
df["iso_code"].dropna(axis=0,inplace=True)

<ipython-input-35-e525126be947>:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [36]:
df1=df[['country','iso_code','vaccines']]

In [37]:
df3 = df1.groupby("country").max()
df3

               iso_code                                   vaccines
country
Albania             ALB                            Pfizer/BioNTech
Algeria             DZA                                  Sputnik V
Andorra             AND                            Pfizer/BioNTech
Angola              AGO                         Oxford/AstraZeneca
Anguilla            AIA                         Oxford/AstraZeneca
...                 ...                                        ...
United Kingdom      GBR        Oxford/AstraZeneca, Pfizer/BioNTech
United States       USA  Johnson&Johnson, Moderna, Pfizer/BioNTech
Uruguay             URY                   Pfizer/BioNTech, Sinovac
Venezuela           VEN                                  Sputnik V
Zimbabwe            ZWE                          Sinopharm/Beijing

[129 rows x 2 columns]

**What country vaccinated more people?**

In [38]:
vaccinations = df.groupby(by="country").sum()
vaccinations.head()

,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million
country,,,,,,,,,
Albania,82830.0,14501.0,2316.0,2897.0,19311.0,2.89,0.50,0.08,6708.0
Algeria,75030.0,0.0,0.0,30.0,69070.0,0.17,0.00,0.00,1568.0
Andorra,20107.0,15145.0,2436.0,0.0,3357.0,26.02,19.60,3.16,43446.0
Angola,6169.0,6169.0,0.0,0.0,6168.0,0.02,0.02,0.00,189.0
Anguilla,8032.0,8032.0,0.0,1421.0,4083.0,53.54,53.54,0.00,272164.0

In [39]:
vaccinations.sort_values(by="total_vaccinations", ascending=False, inplace=True)
vaccinations.head()

,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million
country,,,,,,,,,
United States,2.867864e+09,2.040570e+09,793643798.0,88559147.0,94004025.0,857.50,610.18,237.29,281079.0
United Kingdom,8.293203e+08,7.904030e+08,38917217.0,22081632.0,23986675.0,1221.66,1164.27,57.31,353337.0
India,5.200359e+08,4.580560e+08,61979871.0,27754140.0,24667468.0,37.69,33.18,4.48,17873.0
Israel,3.814093e+08,2.442200e+08,137189251.0,9211106.0,9023802.0,4406.55,2821.55,1585.00,1042545.0
Turkey,2.732764e+08,1.782388e+08,45300233.0,10742277.0,10967584.0,324.04,211.33,53.71,130045.0

**Here we obsereved United states has vaccinated more people**

**What country is vaccinated a larger percent from its population?**

In [40]:
people_vaccinated = df[['country', 'total_vaccinations_per_hundred']]
people_vaccinated.head()
people_vaccinated.max

<bound method NDFrame._add_numeric_operations.<locals>.max of        country  total_vaccinations_per_hundred
0      Albania                            0.00
1      Albania                             NaN
2      Albania                            0.00
3      Albania                            0.01
4      Albania                            0.01
...        ...                             ...
6103  Zimbabwe                            0.24
6104  Zimbabwe                            0.24
6105  Zimbabwe                            0.24
6106  Zimbabwe                            0.24
6107  Zimbabwe                            0.24

[5752 rows x 2 columns]>

In [41]:
people_vacc_grouped = people_vaccinated.groupby("country").mean()
people_vacc_grouped.head()

          total_vaccinations_per_hundred
country
Albania                         0.137619
Algeria                         0.056667
Andorra                         2.891111
Angola                          0.010000
Anguilla                       13.385000

In [42]:
people_vacc_grouped.sort_values(by="total_vaccinations_per_hundred", ascending=False, inplace=True)
people_vacc_grouped.head()

                      total_vaccinations_per_hundred
country
Gibraltar                                  68.111356
Israel                                     52.458929
Seychelles                                 46.474865
United Arab Emirates                       40.175224
Falkland Islands                           31.076667

**Gilbraltat vaccinated large percent of population**